### ISSUE TITLE
Hooknode needs to notify broker node when it has attached a chunk

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/hooknode#24]
Implement hooknode sending message to brokernode that it has attached the chunk by sending a callback URL to hooknode when attaching a chunk

* Alternatively, have brokernode wait for a response. This might have timeout issues if it takes a long time for a chunk to attach

**Comment by AaronVasquez** [comment]
@rfornea Do we still need this? Aren't the cronjobs checking for chunks attached by querying the tangle?

Also, the broker shouldn't trust a hooknode in case it lies about successfully attaching a chunk.

**Comment by AaronVasquez** [comment]
> when above task is completed, un-comment out the commented-out lines in `updateChunksPending` in `DataMap.php`

**Comment by AaronVasquez** [comment]
> Well that depends. For the statuses of a chunk in the database, we were going to have a "pending" status and "unverified" status. Pending is when we have sent the chunk off to the hooknode but have not heard back. Unverified is when the hooknode claims it has attached the TX but we haven't verified that yet. We could conceivably do away with one of these statuses. We don't really have to have both, and we probably wouldn't want to have both if we still plan on forking a curl call to send the trytes to the hooknode, rather than making the process wait. 
> 
> I am leaning towards we just get rid of one of these statuses, and as soon as we send it off to the hooknode, we mark it as "unverified".
- Rebel (from Google Doc Comment)

If we dont need to differentiate between `pending` and `unverified`, I think we should simplify it and reduce the number of states we need to manage.

If we combine them into one state, we wouldn't need to have the hooknode notify the broker, is that correct? The broker would just start verifying in the cron job?

**Comment by rfornea** [comment]
>If we combine them into one state, we wouldn't need to have the hooknode notify the broker, is that correct? The broker would just start verifying in the cron job?  

Yes.  I think we can consolidate these states, and the broker will just start verifying through the cron job.  

This will make it even more important that we have some kind of call on the broker to get the hooknode's load though.

**Comment by AaronVasquez** [comment]
SGTM. I'll remove the `pending` state.
