### ISSUE TITLE
Address memory and/or open connection issues on the hooknode

### ISSUE THREAD

**Issue by AaronVasquez** [oysterprotocol/hooknode#54]
@rfornea commented on [Thu Mar 15 2018](https://github.com/oysterprotocol/brokernode/issues/154)

We have some connections on the hooknode that aren't getting closed.  We fixed one of them, but there seems to be at least one more.  

We have temporary solutions in place for now, but we should address this in the short to medium term.

Priority: Medium

**Comment by automyr** [comment]
Problem seems to be on hook-hook connections. We should look there first.
